### PR TITLE
[fix] Display cards in columns on smaller screens

### PR DESCRIPTION
**Pull request by poenneby**
Demo with Ipad vs Nexus 5X

### CODE REVIEW

**Comment by ModuloM** [comment]
First of all, thanks for this first fix !
Unfortunately, this doesn't fix all the problems with flex box on my layout (related to #24 problems). For example, TOS validation and `sign up` button are hidden in your gif, because card is shrinking (but should not).
I've made some progress on it and have some code to commit. Could you please allow maintainers to push on your PR so I can merge it?
(see documentation [here](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/))

**Comment by poenneby** [comment]
No problem at all, I see now that this does indeed still hide content on the card. I admit it was a pretty quick attempt to fix. 😉
Another point is I don't really have a full environment set up to test the effects of this change elsewhere in the app...
You should have access to commit already.  😃

**Comment by ModuloM** [comment]
Oh ok, I hadn't try before asking sorry.
Finally I've managed to rework layout so it work on Safari / Firefox / Chrome on MacOSX.

I'm going to merge your PR as is, to be able to change the commit message but keep your contribution 😉 (to match [COMMIT guide lines](https://github.com/kodokojo/kodokojo-ui/blob/dev/COMMIT.md))

To be able to test effectively all screens, see how to set up dev environnement with mocked server (note there is a bug if you try to update user that still need to be fix) : see [mocked-api on README](https://github.com/kodokojo/kodokojo-ui#mocked-api)

**Comment by poenneby** [comment]
Thank you sir! 👍

**Pull request merged**
